common:
    lid_topic:  "/os_cloud_node/points"
    # imu_topic:  "/alphasense/imu"
    imu_topic:  "/alphasense/imu_adis"
    # imu_topic:  "/os_cloud_node/imu"
    
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
    
preprocess:
    lidar_type: 3                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 64
    timestamp_unit: 3                 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 4

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     150.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
    
    # normal imu
    # extrinsic_T: [ 0.010254377339094, -0.006657387502187,  0.130729657190738 ]
    # extrinsic_R: [ 0.999975731550615,  0.002455644467473, -0.006519671775555,
    #                0.002457854216372, -0.999996924709319,  0.000330944943738,
    #               -0.006518839042549, -0.000346961314980, -0.999978691950676]
    
    # adis imu
    extrinsic_T: [ 0.000080393859707, -0.037483172013897, -0.162682773531936 ]
    extrinsic_R: [-0.009512419028590,  0.999954499995343, -0.000715418261031,
                  -0.999954688115121, -0.009512152479451,  0.000375062392433,
                   0.000368240159507,  0.000718953594720,  0.999999673752404]
    
    # ouster IMU
    # extrinsic_T: [ 0.022332554919359, -0.012833976130960, -0.019210486493542 ]
    # extrinsic_R: [ 0.999994919712368, -0.000332062687145, -0.003170218261513,
    #                0.000343190739344,  0.999993780035343,  0.003510286419266,
    #                0.003169032907726, -0.003511356575551,  0.999988813740149] 

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
